"""empty message

Revision ID: 109025605d20
Revises: 868ba78933c4
Create Date: 2023-06-28 22:01:04.832801

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from utils import get_current_time


# revision identifiers, used by Alembic.
revision = "109025605d20"
down_revision = "868ba78933c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###
